baseurl: '/linux-to-apples/'
languageCode: en-us
theme: stack
paginate: 5
title: Linux to Apples
disqusShortname: hugo-theme-stack
googleAnalytics: null
DefaultContentLanguage: en
permalinks:
  post: '/p/:slug/'
  page: '/:slug/'
params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: null
  footer:
    since: 2021
    customText: null
  dateFormat:
    published: 'Jan 02, 2006'
    lastUpdated: 'Jan 02, 2006 15:04 MST'
  sidebar:
    emoji: "\U0001F365"
    subtitle: 'Linux to Apples is a place for GNU/Linux enthusiasts to learn and discover anything FOSS related'
    avatar:
      local: false
      src: https://raw.githubusercontent.com/linuxtoapples/Linux-to-Apples/master/ltalogo.png
  article:
    math: false
    toc: true
    license:
      enabled: true
      default: Licensed under MIT
  comments:
    enabled: false
    provider: disqus
    utterances:
      repo: null
      issueTerm: pathname
      label: null
    remark42:
      host: null
      site: null
      locale: null
    vssue:
      platform: null
      owner: null
      repo: null
      clientId: null
      clientSecret: null
      autoCreateIssue: false
    waline:
      serverURL: null
      lang: null
      visitor: null
      avatar: null
      emoji:
        - '🍎'
      requiredMeta:
        - name
        - email
        - url
      placeholder: null
      locale:
        admin: Admin
  widgets:
    enabled:
      - search
      - archives
      - tag-cloud
    archives:
      limit: 5
    tagCloud:
      limit: 10
  opengraph:
    twitter:
      site: null
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
      src: null
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      pre: home
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200
markup:
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
themesDir: themes
baseURL: ''
publishDir: public
